# Generated by Django 4.1.3 on 2024-10-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedinJobs', '0004_historicallinkedinjobs_jobcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkedinjobs',
            name='postulate_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicallinkedinjobs',
            name='postulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinjobs',
            name='postulate_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='linkedinjobs',
            name='postulated',
            field=models.BooleanField(default=False),
        ),
    ]
