# Generated by Django 4.1.3 on 2023-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicaluser_is_staff_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='token_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
