# Generated by Django 4.1.3 on 2023-04-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicaluser_token_password_user_token_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='token_password',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_password',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
