# Generated by Django 4.1.3 on 2023-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_historicaluser_token_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Apellidos'),
        ),
    ]
