# Generated by Django 4.1.3 on 2023-06-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_historicaluser_last_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
