# Generated by Django 4.1.3 on 2023-09-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultTest', '0001_initial'),
        ('selectedjob', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='resultTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultTest.resulttest'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='selectedjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectedjob.selectedjob'),
        ),
        migrations.AlterField(
            model_name='historicalfeedback',
            name='resultTest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resultTest.resulttest'),
        ),
        migrations.AlterField(
            model_name='historicalfeedback',
            name='selectedjob',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='selectedjob.selectedjob'),
        ),
    ]
