# Generated by Django 4.1.3 on 2023-08-04 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resultTest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultSection', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsection',
            name='resultTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultTest.resulttest'),
        ),
        migrations.AddField(
            model_name='resultsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
        migrations.AddField(
            model_name='historicalresultsection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresultsection',
            name='resultTest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resultTest.resulttest'),
        ),
        migrations.AddField(
            model_name='historicalresultsection',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='section.section'),
        ),
    ]
