# Generated by Django 4.1.3 on 2023-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloption',
            name='optionname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='optionname',
            field=models.CharField(max_length=200),
        ),
    ]
